const SHOP_ACTION_TYPES = {
  GET_SHOP_ITEMS: "GET_SHOP_ITEMS",
  HANDLE_INPUT_CHANGE: "HANDLE_INPUT_CHANGE",
  HANDLE_CATEGORY_CHANGE: "HANDLE_CATEGORY_CHANGE",
  HANDLE_FILTER_CHANGE: "HANDLE_FILTER_CHANGE",
};

export default SHOP_ACTION_TYPES;
